language: csharp
mono: none
dotnet: 1.0.4
dist: trusty

services:
  - docker

script:
  - bash ./scripts/travis_build.sh

branches:
  only:
  - master
  - /^[0-9.]+/

cache:
  directories:
  - $HOME/.nuget
