language: node_js
node_js:
  - "0.12"
services:
  - mongodb
before_script:
  - npm install -g gulp
  - npm install -g mocha
  - npm install -g bower
  - bower install
script: gulp build && npm test
cache:
  directories:
  - node_modules
  - bower_components
