language: csharp
# mono: latest
dotnet: 1.0.4
dist: trusty

services:
  - docker

branches:
  only:
  - master
  - /^[0-9.]+/

env:
  - REPO_NAME="ericvan76/kidsprize"

before_install:
#  - ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install)"
#  - /home/linuxbrew/.linuxbrew/bin/brew install gitversion --ignore-depends mono

install:
#  - mono GitVersion.exe /l console /output buildserver /updateAssemblyInfo
  - dotnet --version
  - dotnet restore

script:
  - dotnet build
  - dotnet test ./KidsPrize.Tests/KidsPrize.Tests.csproj
  - dotnet publish -c Release ./KidsPrize.Http/KidsPrize.Http.csproj -o ../docker/assets

before_deploy:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker build docker -t $REPO_NAME
#  - docker tag $REPO_NAME $REPO_NAME:$GitVersion_SemVer
  - if [[ ! -z $TRAVIS_TAG ]]; then docker tag $REPO_NAME $REPO_NAME:$TRAVIS_TAG; fi
  - docker tag $REPO_NAME $REPO_NAME:latest

deploy:
  provider: script
  script: docker push $REPO_NAME
  on:
    all_branches: true