branches:
  only:
  - master

image: ubuntu

environment:
  DOCKER_PASS:
    secure: 9WZpiAD5x5TssAf73a+0CS1S+DE3uVrOc0bKutr8gq0=

init:
  - git config --global core.autocrlf input

stack:
  - docker

install:
  - sudo apt-get install mono-complete
  - sudo apt-get install libcurl3
  - wget https://github.com/GitTools/GitVersion/releases/download/v4.0.0-beta.13/GitVersion_4.0.0-beta0013.zip
  - unzip GitVersion_4.0.0-beta0013.zip -d GitVersion
  - mono GitVersion/GitVersion.exe /l console /output buildserver /updateAssemblyInfo

build_script:
  - dotnet restore
  - dotnet build
  - dotnet publish -c Release ./KidsPrize.Http/KidsPrize.Http.csproj -o ../docker/assets

test_script:
  - dotnet test ./KidsPrize.Tests/KidsPrize.Tests.csproj

deploy_script:
  - docker login -u="ericvan76" -p="$DOCKER_PASS"
  - docker build docker -t ericvan76/kidsprize
  - docker tag ericvan76/kidsprize ericvan76/kidsprize:$GitVersion_SemVer
  - docker tag ericvan76/kidsprize ericvan76/kidsprize:latest
  - docker push ericvan76/kidsprize
