version: '2'
services:
  https-portal:
    image: steveltn/https-portal
    ports:
      - '80:80'
      - '443:443'
    restart: always
    environment:
      DOMAINS: 'secure.kids-prize.com -> http://idsvr:4999/, api.kids-prize.com -> http://api:5000/'
      # STAGE: 'production'
      # FORCE_RENEW: 'true'
  api:
    build:
      context: src/KidsPrize.Http
    depends_on:
      - db
    ports:
     - '5000:5000'
    volumes:
      # - ./appsettings-api.json:/root/appsettings.Production.json
      - ./logs:/root/logs
    restart: always
    environment:
      ASPNETCORE_URLS: http://*:5000
  idsvr:
    build:
      context: src/IdentityServer
    depends_on:
      - db
    volumes:
      # - ./appsettings-idsvr.json:/root/appsettings.Production.json
      - ./logs:/root/logs
    restart: always
    environment:
      ASPNETCORE_URLS: http://*:4999
  db:
    image: postgres
    ports:
      - '5432:5432'
    # volumes:
    #  - ./data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: kidsprize
      POSTGRES_PASSWORD: password