version: '2'
services:
  api:
    build:
      context: src/KidsPrize.Http
    ports:
      - "5000:5000"
    volumes:
      - ./config/api:/root/Config
      - ./logs:/root/logs
    depends_on:
      - db
      - idsvr
    restart: always
    environment:
      ASPNETCORE_ENVIRONMENT: Development
  idsvr:
    depends_on:
      - db
    build:
      context: src/IdentityServer
    ports:
      - "4999:4999"
    volumes:
      - ./config/idsvr:/root/Config
      - ./logs:/root/logs
    restart: always
    environment:
      ASPNETCORE_ENVIRONMENT: Development
  db:
    image: postgres
    volumes:
      - data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
volumes:
  data: