version: '3'
services:

  https-portal:
    image: steveltn/https-portal:1.1
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./ssl_certs:/var/lib/https-portal
      - ./vhosts:/var/www/vhosts
    restart: always
    environment:
      - STAGE=production

  kidsprize:
    image: ericvan76/kidsprize:latest
    volumes:
      - ./logs:/service/logs
    restart: always
    environment:
      - 'VIRTUAL_HOST=kidsprize-api.fanstek.com'
      - 'kidsprize:ConnectionStrings:DefaultConnection=Server=postgres;Port=5432;Database=kidsprize;User Id=kidsprize;Password=password;'
      - 'kidsprize:JwtBearerOptions:Authority=https://apperic.auth0.com/'
      - 'kidsprize:JwtBearerOptions:Audience=<audience>'
      - 'kidsprize:HealthCheckPingUrl=<health-check-ping-url>'

  postgres:
    image: postgres:9.6
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    restart: always
    environment:
      - POSTGRES_USER=kidsprize
      - POSTGRES_PASSWORD=password
