version: '2'
services:
  combined:
    build:
      context: ../src
    ports:
      - "4999:4999"
      - "5000:5000"
    volumes:
      - /Users/eric/Dropbox/Repos/kids-prize/docker/appsettings-idsvr.Development.json:/root/idsvr/appsettings.Development.json
      - /Users/eric/Dropbox/Repos/kids-prize/docker/appsettings-api.Development.json:/root/api/appsettings.Development.json
      - /Users/eric/Dropbox/Repos/kids-prize/docker/logs:/root/idsvr/logs
      - /Users/eric/Dropbox/Repos/kids-prize/docker/logs:/root/api/logs
    depends_on:
      - db
    restart: always
    environment:
      ASPNETCORE_ENVIRONMENT: Development
  db:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: kidsprize
      POSTGRES_PASSWORD: password
volumes:
  data: {}