version: '2'
services:
  api:
    build:
      context: ../src/KidsPrize.Http
    ports:
      - "5000:5000"
    volumes:
      - ./appsettings-api.Prodcution.json:/root/appsettings.Prodcution.json
      - ./logs:/root/logs
    depends_on:
      - db
      - idsvr
    restart: always
    environment:
      ASPNETCORE_URLS: http://*:5000
  idsvr:
    depends_on:
      - db
    build:
      context: ../src/IdentityServer
    ports:
      - "4999:4999"
    volumes:
      - ./appsettings-idsvr.Prodcution.json:/root/appsettings.Prodcution.json
      - ./logs:/root/logs
    restart: always
    environment:
      ASPNETCORE_URLS: http://*:4999
  db:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: kidsprize
      POSTGRES_PASSWORD: password
volumes:
  data: {}